export const PRODUCTS = [
  {
    id: "10",
    imageUrl: "/images/p_1.png",
    title: "Syltherine",
    description: "Stylish cafe chair",
    price: "2500000",
    otherPrice: "3.500.000",
    type: "DISCOUNTED",
    typeValue: "-30%",
  },
  {
    id: "20",
    imageUrl: "/images/p_2.png",
    title: "Leviosa V3",
    description: "Stylish cafe chair",
    price: "2500000",
    otherPrice: "3.500.000",
    type: "DISCOUNTED",
    typeValue: "-30%",
  },
  {
    id: "30",
    imageUrl: "/images/p_3.png",
    title: "Lolito Bilo",
    description: "Luxury big sofa",
    price: "7000000",
    otherPrice: "14.000.000",
    type: "DISCOUNTED",
    typeValue: "-50%",
  },
  {
    id: "40",
    imageUrl: "/images/p_4.png",
    title: "Respira Xen",
    description: "Outdoor bar table and stool",
    price: "500000",
    otherPrice: "",
    type: "NEW",
    typeValue: "New",
  },
  {
    id: "50",
    imageUrl: "/images/p_5.png",
    title: "Grifo Xen",
    description: "Night lamp",
    price: "1500000",
    otherPrice: "",
    type: "NORMAL",
    typeValue: "",
  },

  {
    id: "60",
    imageUrl: "/images/p_6.png",
    title: "Muggo Buni",
    description: "Small mug",
    price: "150000",
    otherPrice: "",
    type: "NEW",
    typeValue: "New",
  },
  {
    id: "70",
    imageUrl: "/images/p_7.png",
    title: "Pingky",
    description: "Cute bed set",
    price: "7000000",
    otherPrice: "14.000.000",
    type: "DISCOUNTED",
    typeValue: "-50%",
  },

  {
    id: "80",
    imageUrl: "/images/p_8.png",
    title: "Potty",
    description: "Minimalist flower pot",
    price: "500000",
    otherPrice: "",
    type: "NEW",
    typeValue: "New",
  },
  {
    id: "90",
    imageUrl: "/images/p_1.png",
    title: "Syltherine v2",
    description: "Stylish cafe chair",
    price: "2500000",
    otherPrice: "3.500.000",
    type: "DISCOUNTED",
    typeValue: "-30%",
  },
  {
    id: "100",
    imageUrl: "/images/p_2.png",
    title: "Leviosa V2",
    description: "Stylish cafe chair",
    price: "2500000",
    otherPrice: "3.500.000",
    type: "DISCOUNTED",
    typeValue: "-30%",
  },
  {
    id: "110",
    imageUrl: "/images/p_3.png",
    title: "Lolito Vilo",
    description: "Luxury big sofa",
    price: "7000000",
    otherPrice: "14.000.000",
    type: "DISCOUNTED",
    typeValue: "-50%",
  },
  {
    id: "120",
    imageUrl: "/images/p_4.png",
    title: "Respira Uno",
    description: "Outdoor bar table and stool",
    price: "500000",
    otherPrice: "",
    type: "NEW",
    typeValue: "New",
  },
  {
    id: "130",
    imageUrl: "/images/p_5.png",
    title: "Grifo Yon",
    description: "Night lamp",
    price: "1500000",
    otherPrice: "",
    type: "NORMAL",
    typeValue: "",
  },

  {
    id: "140",
    imageUrl: "/images/p_6.png",
    title: "Muggo Sacpe",
    description: "Small mug",
    price: "150000",
    otherPrice: "",
    type: "NEW",
    typeValue: "New",
  },
  {
    id: "150",
    imageUrl: "/images/p_7.png",
    title: "Pingky Hoi",
    description: "Cute bed set",
    price: "7000000",
    otherPrice: "14.000.000",
    type: "DISCOUNTED",
    typeValue: "-50%",
  },

  {
    id: "160",
    imageUrl: "/images/p_8.png",
    title: "Potty Been",
    description: "Minimalist flower pot",
    price: "500000",
    otherPrice: "",
    type: "NEW",
    typeValue: "New",
  },
];
